### ISSUE TITLE
Delete Group vs Quit Group - They appear to do the same thing.

### ISSUE THREAD

**Issue by EJansenMSFT** [bbernhard/signal-cli-rest-api#112]
I've written PowerShell functions for almost all of the API functions, and in my testing, it appears that deleting a group, which looks like this for how I've written it:

 
![image](https://user-images.githubusercontent.com/72317762/111744710-0828db80-8862-11eb-8540-8b79558f26f3.png)

does the exact same thing as quitting a group, which looks like this for how I've written it:

![image](https://user-images.githubusercontent.com/72317762/111744840-36a6b680-8862-11eb-90b3-b4890c12a6b4.png)

In both scenarios, the group still shows up when I list all of the groups, the phone number just isn't a member anymore.  Even if I create a group on my phone, add the other number, make that number an admin, and then try to delete the group with the function, it just removes the number from the group and the remaining members stay in it.  Didn't know if that was a bug or if there's some other difference that I'm unaware of?

Also, while on the topic of groups, I can create groups, and it'll show up when I list the groups, but it only has an ID, no name.  Not sure if there's some other key value pair that should be added to the body?  The example just has ID : 'string'.

**Comment by bbernhard** [comment]
> In both scenarios, the group still shows up when I list all of the groups, the phone number just isn't a member anymore. Even if I create a group on my phone, add the other number, make that number an admin, and then try to delete the group with the function, it just removes the number from the group and the remaining members stay in it. Didn't know if that was a bug or if there's some other difference that I'm unaware of?

I _think_ that's how signal-cli deals with groups - but not sure if that's works as designed or a bug. In order to actually verify whether that behavior is signal-cli specific or introduced by the REST API wrapper, you can do the following: 

* enable the debug mode with: `curl -X POST -H "Content-Type: application/json" -d '{"logging": {"level": "debug"}}' 'http://127.0.0.1:8080/v1/configuration'`. The docker container is now in debug mode and will print some additional debug information to the docker container log file. In case you want to reset the log level, either use the REST API endpoint again with a different log level, or just restart the docker container. The log level will automatically be resetted when the container gets restarted. 

* execute the REST API call you want to debug
* have a look at the container log file. It tells you how you can connect to the docker container and which command you need to invoke in order to manually execute a signal-cli command.

If the REST API call behaves different to the manual invocation of signal-cli, then it's a REST API bug. In case the REST API wrapper and the direct signal-cli command behave the same, it's related to the internals of signal-cli. In that case I can't do much - you would need to create a issue in the [upstream repository](https://github.com/AsamK/signal-cli).

> Also, while on the topic of groups, I can create groups, and it'll show up when I list the groups, but it only has an ID, no name. Not sure if there's some other key value pair that should be added to the body? The example just has ID : 'string'.

Oh, there's something missing in the swagger documentation. Thanks for the info, I'll fix that!

The request should look like:

`curl -X POST -H "Content-Type: application/json" -d '{"name": "my test group", "members": ["<member1>"]}' 'http://127.0.0.1:8080/v1/groups/<number>'`

**Comment by EJansenMSFT** [comment]
> The request should look like:

curl -X POST -H "Content-Type: application/json" -d '{"name": "my test group", "members": ["<member1>"]}' 'http://127.0.0.1:8080/v1/groups/<number>'

Awesome, that did the trick.  Also wrote for getting / setting debug logging levels.  Still digging into the delete vs quit group, but i'll post more as I learn more.

Thanks!

**Comment by EJansenMSFT** [comment]
OK, with debugging turned on, I did a delete group, which apparently runs a 'quitGroup' with the Signalcli:

![image](https://user-images.githubusercontent.com/72317762/111892296-82776e00-89d0-11eb-95a5-ef0fbbfc9059.png)

**Comment by EJansenMSFT** [comment]
I guess there isn't a delete group command:

![image](https://user-images.githubusercontent.com/72317762/111895495-51effe00-89e9-11eb-9ba9-a8c0a5108a1c.png)

Guess, I'll be removing Delete-SignalGroup from the module.

**Comment by bbernhard** [comment]
I just checked inside the sourcecode - I am also calling the `quitGroup` command inside the `DELETE` endpoint. So, actually the `DELETE` command isn't really deleting something. :/

I guess the cleanest solution would probably be to remove the `DELETE` endpoint, but I am a bit afraid that this might break existing setups (e.g maybe someone used the `DELETE` endpoint for quitting a group and by removing that functionality I would break those setups). So, I think the safest thing to do is maybe to leave it in there (and hope that signal-cli maybe adds that functionality at some point). Hope that works for you :)

**Comment by EJansenMSFT** [comment]
Oh, definitely agree, at this point, I wouldn't remove it from your side.  I was just talking about my removing it from my module as a separate function / cmdlet.

**Comment by bbernhard** [comment]
> Oh, definitely agree, at this point, I wouldn't remove it from your side. I was just talking about my removing it from my module as a separate function / cmdlet.

yeah, I think that makes sense :+1:. If you are interested in this functionality, you could create an issue in the signal-cli repository (if no issue for that already exists). Once it is implemented upstream, I could expose the functionality also via the REST API.

**Comment by EJansenMSFT** [comment]
Hmm, maybe there is a Group Delete:

![image](https://user-images.githubusercontent.com/72317762/112258573-19e0f900-8c3d-11eb-8c30-772f225e45b9.png)

Found that _Api.go_ file in the signal-cli-config folder, as I was looking for a way to migrate that info to another container on a different host.
