### ISSUE TITLE
Linked device

### ISSUE THREAD

**Issue by christophebe** [bbernhard/signal-cli-rest-api#124]
Hello, 

I don't want to register a new phone to Signal. In this case, is it not sufficient to link my mobile with http://127.0.0.1:8080/v1/qrcodelink?device_name=xxxx ?

After doing this. I see the linked device on my mobile but when I send a message from the REST API, I got this : {"error":"Error while checking account +32xxxxxx: Authorization failed!\n"}% 

Do I miss a step ? 

Thanks 
Christophe

**Comment by bbernhard** [comment]
In theory that should be everything that's needed. `signal-cli` seems to be behave a bit weirdly when you first register a number and then link a device. So in case you've tried the `register` endpoint before, it might be worth a try to start from scratch by removing the whole config directory and then linking the device. (see also this issue here: https://github.com/bbernhard/signal-cli-rest-api/issues/35)

Another thing you could try is to call the `receive` endpoint after linking the device. `signal-cli` mentions in its [man page](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc) that calling the `receive` regularily is recommended.

**Comment by christophebe** [comment]
Thank you for the information. It works now. 

Indeed, I had registered my number before to test
