### ISSUE TITLE
expose addDevice command

### ISSUE THREAD

**Issue by steveredden** [bbernhard/signal-cli-rest-api#165]
### Feature Request
Hoping to add the desktop app as a secondary client via the [Linking other devices](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)) page's 'Add another device' command:

```
signal-cli -u USERNAME addDevice --uri "tsdevice:/…"
```

**Comment by jaytea33** [comment]
+1 for this feature. I was struggling to link signal-desktop to my HA instance, as I didn't see any references to it in the Swagger api doc, so that makes sense that it's not currently possible.

**Comment by steveredden** [comment]
@jaytea33 fyi I added an issue to the HA repo with instructions, if you haven’t already got it figured out:

https://github.com/haberda/signal-addon/issues/12#issue-1025952404

**Comment by jaytea33** [comment]
Dude thank you so much. Those instructions were simple and concise; I now have it linked. Portainer was definitely the missing piece for the needed container access to run those commands. I used it in the past and removed it because I thought it was deprecated and I didn't realize it was still being maintained. This will definitely come in handy for the future.

**Comment by peteh** [comment]
I would +1 this feature request too, even the workaround should work too.
