### ISSUE TITLE
Losing WebSocket connection

### ISSUE THREAD

**Issue by thbiela** [bbernhard/signal-cli-rest-api#185]
### The problem

Hi,

first of all: thanks for this great addon! I am using the API in a dockerized Synology x64 environment.

Unfortunately, I am having trouble using the websocket connection. I am connecting using NodeRed but I am losing a lot of incoming messages. In the logs I can see this error messages:

`ERRO[0310] Couldn't write message: websocket: close sent `

![image](https://user-images.githubusercontent.com/33088153/143874386-f667099a-42b1-4f38-96e9-431d855b6ad6.png)

Any ideas?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Can you please try to use a different websocket client (e.g [wscat](https://github.com/websockets/wscat)) in order to rule out that it's something with NodeRed. With `wscat` you should be able to connect with:

`wscat -c 127.0.0.1:8080/v1/receive/<your registered signal number> --show-ping-pong --slash`

Does that work?

**Comment by georg90** [comment]
I can confim that `wscat` is working as expected. What helped me, was to update my > 1 year old Node-Red docker image. With the latest image from DockerHub it works like a charm :)
