### ISSUE TITLE
error Captcha required for verification

### ISSUE THREAD

**Issue by VincentDugard** [bbernhard/signal-cli-rest-api#19]
Hi ! When I run the CURL post to verify phone number :
`curl -X POST -H "Content-Type: application/json" 'http://192.168.255.1:8080/v1/register/+336xxxxxxxx'`

I get  : 
`{"error":"Captcha required for verification (null)\n"}`

any idea ?

**Comment by bbernhard** [comment]
Hi,

unfortunately there isn't much that I can do here. The `signal-cli-rest-api` is just a small wrapper around the the `signal-cli` commandline tool, which does all the magic. There already exists a ticket here: https://github.com/AsamK/signal-cli/issues/251 

What I've read so far on the Signal Messenger forums about the google captcha integration is, that many users are (obviously) not really happy about that move due to privacy concerns. So it's possible that google captchas will be replaced by something else in the future. According to the Signal Messenger developers, the captcha is only necessary when users register on a network where additional protection mechanisms are required.

So, if it's possible for you, the easiest thing would probably be to try to get a different public ip for the registration. Once the number is registered, you should be able to transfer the identity to your actual host.

**Comment by Vedeneb** [comment]
Hi,

signal-cli has a `--captcha` option for the register command. A token must be passed which can be generated by completing the captcha on https://signalcaptchas.org/registration/generate.html (See here for info: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#commands)

Could you add this option to the REST API? That should fix the issue.

**Comment by bbernhard** [comment]
Thanks for the info! It's now implemented and will be shipped with the next version. :)

**Comment by Vedeneb** [comment]
Wow that was fast, thanks a lot!

**Comment by ronaldt80** [comment]
I registered a phone number without trouble this weekend; however wanted to replace it with a dedicated sim card today and got the "captcha error" - tried to follow the above instructions but run into two problems:

1- when looking at the signalcaptchas.org site I do not get a captcha picture; also the developer tools section shows errors:

`Failed to launch 'signalcaptcha://[CODEWITHLETTERSANDNUMBERS]' because the scheme does not have a registered handler.`

2 - provided I get the right code, where do i add it in the curl command to register the phone number?

Many thanks!

**Comment by bbernhard** [comment]
> I registered a phone number without trouble this weekend; however wanted to replace it with a dedicated sim card today and got the "captcha error" - tried to follow the above instructions but run into two problems:
> 
> 1- when looking at the signalcaptchas.org site I do not get a captcha picture; also the developer tools section shows errors:
> 
> `Failed to launch 'signalcaptcha://[CODEWITHLETTERSANDNUMBERS]' because the scheme does not have a registered handler.`
> 
> 2 - provided I get the right code, where do i add it in the curl command to register the phone number?
> 
> Many thanks!

Have you tried opening the site in a private browser window? For me that way it works.

regarding 2:

Oh, looks like the documentation is incomplete in that regard. It should be:

```curl -X POST -H "Content-Type: application/json" --data '{"captcha": "<captcha from developer console>"}' 'http://127.0.0.1:8080/v1/register/<+your number>'```

**Comment by ronaldt80** [comment]
thanks for the quick response. I indeed now do get the typical pictures to click on. 

Oddly though the same message appears - "the scheme does not have a registered handler" - I nonetheless copied the code (very long... see below) but not successful. 

Wonder what causes this captcha trigger in the first place. I run the container on home assistant in my private network, no vpn whatsoever.


`03AGdBq254OjDao8fylddC4-VM_EHcn3vwODmBJKJDMLLDMPwAWl-9MRWcXuvRIz6dXuTr63AG1mQklRpowqrdXf1rHp9JNfjDWEWgXw42IpVDcf-JMCYjhu59ieCOSOAhfMqF97eiSAnu2IEyxA5lkIcysU1s0xE841bjQN02COOJEVZ4XTxgNq0AimWAfty5TmPEMyRu_KjikObw6eQoG-UFvpnFkRqHOuAOM4om4eeo4l8HrkTvjWeazD4p65gaVVbjAdJySDXpMZhJKkMLDxggDAm9uHAN639s76zgTDh4Ir2DnboP-QqmXZS6myCnUJsxFINrPCldUME42crmXDYXcjkbO1ujzQGKgybl73S1OLwG9cfMQmWsobtzbiQ0VqUaEpk7Q-VFPvaCxKRP2-cWhNCjYDxoxnwFMF-pO-05v8EWEgDCdbRIV3KVadTelgSyplkm8hv9XTzYF8cxgQD80hBfOjmu7E3gfIMyEIJPXoqaKpIhw2Q`

**Comment by ronaldt80** [comment]
Never mind - tried 4 more times and the last one worked!

**Comment by The-May** [comment]
> Never mind - tried 4 more times and the last one worked!

What did you get after registering? also "Null"? Did they send you an SMS?
Now after finding out how to get the captcha "code" i seem to get "null" It looks bad

![image](https://user-images.githubusercontent.com/47433911/107029780-e8f15580-67af-11eb-9e84-6511391e1b85.png)

Captcha has to be right, otherwise I would get this:
![image](https://user-images.githubusercontent.com/47433911/107030017-408fc100-67b0-11eb-90fa-ea61e26e3456.png)

**Comment by bbernhard** [comment]
> > Never mind - tried 4 more times and the last one worked!
> 
> What did you get after registering? also "Null"? Did they send you an SMS?
> Now after finding out how to get the captcha "code" i seem to get "null" and I get no Message.... It looks bad
> 
> ![image](https://user-images.githubusercontent.com/47433911/107029780-e8f15580-67af-11eb-9e84-6511391e1b85.png)
> 
> Captcha has to be right, otherwise I would get this:
> ![image](https://user-images.githubusercontent.com/47433911/107030017-408fc100-67b0-11eb-90fa-ea61e26e3456.png)

`null` should indicate that everything worked. (I'll change the response message to something else in one of the next releases, as `null` was a really bad choice).

Afaik, per default you should get an SMS.

**Comment by bbernhard** [comment]
As it worked for @ronaldt80 I guess it could also be a Signal Service. See also: https://github.com/AsamK/signal-cli/issues/300

**Comment by EJansenMSFT** [comment]
Does anyone know what I'm messing up here?

![image](https://user-images.githubusercontent.com/72317762/110255813-9e582a00-7f63-11eb-888e-9272756ea7fc.png)

This is the code that I get:

![image](https://user-images.githubusercontent.com/72317762/110255835-c5166080-7f63-11eb-8b15-cd8f0ad1399e.png)

Note that in the first image above, I've removed what's highlighted.

Also, when I run it, this is the error that I see on the container:

![image](https://user-images.githubusercontent.com/72317762/110255867-f4c56880-7f63-11eb-9d1c-dbabbad43ef6.png)

The 'c' that it's referencing is the c in captcha that we're supposed to use, per the instructions that I've been using / what I see other using.  I'm clearly not doing something right though.  Any help would be much appreciated.

Thanks,
Eric

**Comment by EJansenMSFT** [comment]
I had a bit of a breakthrough / at least got past the error above.  My issue appears to be because I'm using a PowerShell Terminal and the use of the ' vs the " can have a big impact depending on what's between them.  Anyhow, now I'm being prompted for a password.  Not sure what that's about?  Granted, I'm using my existing phone number in the registration attempt, that I currently use for Signal.  I just downloaded signal yesterday so I have no idea what I'm doing. :)  Made it this far though.  I just want to send secure messages via PowerShell.  Anyhow here were the next 4 attempts:

![image](https://user-images.githubusercontent.com/72317762/110256556-84204b00-7f67-11eb-9bd6-01873760bd0e.png)

What is user 'Tformat'?

Thanks,
Eric

**Comment by EJansenMSFT** [comment]
This is the closest that I've been thus far:

I generated a new captcha from earlier in playing around, so it does differ, but I just don't know what syntax I'm messing up.  Here's the latest Captcha:

![image](https://user-images.githubusercontent.com/72317762/110259176-63aabd80-7f74-11eb-888e-06d2712f95df.png)

Here's the latest attempt, which says that the captcha is invalid:

![image](https://user-images.githubusercontent.com/72317762/110259210-82a94f80-7f74-11eb-89c2-6ccfa8347806.png)

Thanks for any guidance that anyone has!

**Comment by misterakko** [comment]
Trying to reach https://signalcaptchas.org/registration/generate.html  results in a totally blank page on Chrome for me.
Safari kind-of worked, showed the captcha and then replied with an error message related to an impossible URL. Copying the last fragment of the URL (after ://) worked.
I'm leaving this here in the hope it helps somebody else.

**Comment by Supercalafragalisticexpialadoshus** [comment]
I'm having a similar challenge to Misterakko.  After days of troubleshooting & 2 linux distros I successfully got signal-cli to work correctly.  I then put in the command:  bin/signal-cli -u +1XXXxxxXXXX register
I got this response:

Captcha required for verification, use --captcha CAPTCHA
To get the token, go to https://signalcaptchas.org/registration/generate.html
Check the developer tools (F12) console for a failed redirect to signalcaptcha://
Everything after signalcaptcha:// is the captcha token.

When I went to the URL in firefox there was just a blank screen. So I tried it in Safari (using PlayOnLinux) but Safari gave the error:
---Safari can’t open the page “https://signalcaptchas.org/registration/generate.html” because Safari can’t establish a secure connection to the server “signalcaptchas.org”---[](url)

I was able to get the info from the QR-code on signal using a [webpage](https://zxing.org/w/decode) and it returned---  tsdevice:/?uuid=.....(string of letters/numbers)
I opened the signal-cli file thinking that I might be able to put the QR-code in directly but interpreting that level of code is outside of my skillset.
Does anybody know what I can do to get it functioning at this point?

**Comment by bbernhard** [comment]
> I'm having a similar challenge to Misterakko. After days of troubleshooting & 2 linux distros I successfully got signal-cli to work correctly. I then put in the command: bin/signal-cli -u +1XXXxxxXXXX register
> I got this response:
> 
> Captcha required for verification, use --captcha CAPTCHA
> To get the token, go to https://signalcaptchas.org/registration/generate.html
> Check the developer tools (F12) console for a failed redirect to signalcaptcha://
> Everything after signalcaptcha:// is the captcha token.
> 
> When I went to the URL in firefox there was just a blank screen. So I tried it in Safari (using PlayOnLinux) but Safari gave the error:
> ---Safari can’t open the page “[https://signalcaptchas.org/registration/generate.html”](https://signalcaptchas.org/registration/generate.html%E2%80%9D) because Safari can’t establish a secure connection to the server “signalcaptchas.org”---
> 
> I was able to get the info from the QR-code on signal using a [webpage](https://zxing.org/w/decode) and it returned--- tsdevice:/?uuid=.....(string of letters/numbers)
> I opened the signal-cli file thinking that I might be able to put the QR-code in directly but interpreting that level of code is outside of my skillset.
> Does anybody know what I can do to get it functioning at this point?

Have you tried opening the URL in a private window? I did get a blank screen in firefox, but it worked for me when I opened the URL in a firefox private window.

**Comment by Supercalafragalisticexpialadoshus** [comment]
That is a good suggestion Bbernhard.  But I had no greater success.  I tried the signalcaptchas.org URL in a private window and still saw only a blank window.  What I wonder is if there's a way to get the QR-code -- tsdevice:/?uuid... to work?  Maybe that would be a better option.

**Comment by bbernhard** [comment]
> That is a good suggestion Bbernhard. But I had no greater success. I tried the signalcaptchas.org URL in a private window and still saw only a blank window. What I wonder is if there's a way to get the QR-code -- tsdevice:/?uuid... to work? Maybe that would be a better option.

That's strange. Did you use this URL(https://signalcaptchas.org/registration/generate.html) in a private window? 

You can use the QR code, but the QR code is doing something entirely different. With the QR code you can link a already registered Signal number to your docker container whereas with the `register` endpoint you are registering a new number with the Signal service.

**Comment by Supercalafragalisticexpialadoshus** [comment]
Yes. I used signalcaptchas.org and got the same blank page.
Interestingly I already have a number registered (long story, a friend let me use his phone) and I have a 6-digit code. But when my drive crashed & I had to re-install, it wouldn't show an option to put either number or 6dig number in- just the QR code screen

**Comment by proggaras** [comment]
Actually I can fulfill the capture. But it is not 100% clear for me which part of the string I have to copy in to the API call: "captcha":"captcha value"

It seems a bit longer as I found in previous documentations. 

signalcaptcha://signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQUGMdQKg_3rpSPgAZcX0c1iNtP2mwuibyPM49jRKcxYbqp4YcoJFsrU5qQobKQRXHjzSgF8S01nf3Bc5B8w_Y4182Hmv4fV2s82dJLtDCFL4VZ9UmWQ0qQ0VRFXY8injkcyM4X0x2iNpAc_bfEId2eOpKVs6XX2ZQQSXG2F1IyGLLL-yK08iSiImsfKBw8xQAw3WPj5uO3gAjrapKiisrgPNp_AzodVglnI-8icGxePsylIUlBJAxu4SEvNg72EncoGTV0W8MElWQI8hQZrDBu4FfbGcagWOfzhM6Vn0_jwvIKN50ZQ9nwhszkjI-31EyxrQa45hdoQLEW-2VlLldovjsVSF2rvip3-Qh42-MQe3xN-Z6jZIRq-8oVNHnSZaj1jdI12wBWwKAb7XCBUVVjdjaMJ6BRfNoJh3LJU0ecrDlgw0pHSn4dgDpQQDmJGzthOY6swYw9_bi1fk_ZP5uvddj18DxOrpOCUXEutrSdQ_2VJqz4qct5laW-MtWU_HG-Eu6_Bww_8znxceNZLR1aA1-O-Mo3WeilYjW_R47jKcXagjfXH4mFLlFRd4PaoA4KvOVdywWKgovwvwOSDwzRdI3xybIdHke8h6f8ZerguWGuGnwwO9fx0n54i5xeO7D6Il-l2Z8YMaPAxQkPbL_u1oGSo1JALQypzFpgThwUZbcCX3O2VYq7UJ5t4k39anng3tV-18jF4Vg2qOO-bYeRyVmY5Lt6Hjbi841X3RSoul14jaEUF3w-1ILFP4zwYIYCnCmzKXG2G9Z9PJUXvkqpfk_KbMEeMyqKg0zCtLBtx88OdBZOIDhvz_CDMl3CPGJUMWyJ57DOQb0wuDu7fIg-Tx2sv0hmKstwZjLOe5nELcaRuOLOVQHfozkA70roNE9q_LsPahF0_FYEL8kRoiEuAYmq3oq0s8H9O3mU8FQvISlYYj35Nx5Af2zIbJVGbg9dt9LshFWwzETarMV9RQhgiY5DqB5qARBCeirq3Y5Bc_zJgyQvJyz75DlHeCasboUUeLmqCxQ1UBT0G6yb69UEoBhotFBVkjH5e02UmMDDv_oe_BliL3YwjOrprLN4B9TM8t5A_kws9AsAvz4B3raDlhvOfGcuS7xV4p3S3HrgLYalX6ZDoDisUybKkGta09UnKjb2ZBcuhyvZh1KbrYOceyLRj7aSpm-62HBAFA3JBcwyAEsorT0jYTYDXKfUmPU8qcQISAr4ieLJq_C2yvZ9XswA1JewS0eFJGYrqvOOZbi8-cLuA3ey1J5oBntMRKk8RDd_mVWfYAxvFsBZaeGV2i4FIb8PtlWcWVQ7aMxiPbgksh3xEmyHDZLV9RnTnOZGGIMgArVFzIUE4in5P-pa8UhxPO2KrwCLQU6Y9Ub_m5f5uaTfaORrRk4ok4r9Pb6NqbOEn8rmHYMhJJL0s_Gb835sypoCRC1HfD6LwMQ9mgVBA1AZZOB6cOMHnbGFuZPf3Uxd-C0M7zfAMYIRnNZ_S4icQmr73Aqr_iaXnaT_QMtyy-UrMJMK8sc083KfyIFFMIuABSo2-TxaBb_gQE2dzS7asEA9rJnOFGpo7_x_SIuJmEEp6EfPMLtQYH5tfnmFSN6OLjRZhRDEWKwyjE1i7ec8wkzDYLbE1mqbdP-X91R8V3Xd81BdAJVZuk3lo91j3fd3SAG37mePz5wAtxSKGyqcLWBCHUAgJ6C4FTx7L3fA8tlx_1VSjZXhwzmSikMeoc2hhcmRfaWTOAzGDb6JwZAA.8ZZdBGJND-XpiSh-Tf0zeMLzYeSZaixKpzpVSQfuUFY

**Comment by Quantumint** [comment]
> It seems a bit longer as I found in previous documentations.
> 

I have the same problem. Cutting the string after signalcaptcha:// does not work. Neither cutting after "registration". Every time I get "invalid captcha". After I few tries I get "Failed to register: [429] Rate limit exceeded: 429 (RateLimitException)" that I guess mean that too many requests were made.
