### ISSUE TITLE
Callback when a message is received

### ISSUE THREAD

**Issue by KY-7** [bbernhard/signal-cli-rest-api#192]
Hi @bbernhard and the whole team,

First, thanks for the great job and happy new year!

I'm wondering if it's possible to make a callback when a message is received by a specific account.
More specifically, during registration, a callback url is specified. Later, when messages are received for account on the signal-cli side,
then the callback url is called. This callback could be a simple http get to tell the calling system that messages were received or it could be an http post that sends all the received messages back to this calling system.

Few related questions:
- Is signal-cli notified somehow when some messages (like replies) are available?
- Is the signal-cli storing replies somehow till they are read?
- if you think this feature is realistic, could you point out where I can look in the code till it's implemented (hopefully)?

**Comment by bbernhard** [comment]
Happy new year!

If you switch to the `json-rpc` Mode, after you've registered your number you can use a websocket connection to receive messages. e.g: In order to listen for incoming messages you can use [wscat](https://github.com/websockets/wscat) like this: `wscat -c 127.0.0.1:8080/v1/receive/<your registered signal number> --show-ping-pong --slash`

> Is signal-cli notified somehow when some messages (like replies) are available?

see the websocket endpoint above.

> Is the signal-cli storing replies somehow till they are read?

As far as I know, `signal-cli` doesn't store any messages on the filesystem. Until they are received, they are stored on the Signal Server.

**Comment by KY-7** [comment]
Thanks!
I see that I need a separate websocket client for automatically receiving messages but that's fine.
