### ISSUE TITLE
Couldn't create QR code: no data to encode

### ISSUE THREAD

**Issue by RadovanPelka** [bbernhard/signal-cli-rest-api#231]
### The problem

<img width="638" alt="image" src="https://user-images.githubusercontent.com/29738200/159362807-0a0b0bb0-0f42-49f6-b559-a5199c629111.png">

<img width="892" alt="image" src="https://user-images.githubusercontent.com/29738200/159362899-51b722b2-8ab3-41fd-9c85-40c8b9143ef5.png">

any idea?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
That's odd. Can you please enable the [Debug Mode](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and invoke the `signal-cli` command directly. Do you see any errors?

**Comment by RadovanPelka** [comment]
> That's odd. Can you please enable the [Debug Mode](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and invoke the `signal-cli` command directly. Do you see any errors?

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/29738200/163465329-9996705b-910a-4b99-8904-649f63d94c71.png">
see...

**Comment by bbernhard** [comment]
Can you please give this test image a try: `bbernhard/signal-cli-rest-api:0.106-dev`

**Comment by RadovanPelka** [comment]
> Can you please give this test image a try: `bbernhard/signal-cli-rest-api:0.106-dev`

<img width="915" alt="image" src="https://user-images.githubusercontent.com/29738200/163669732-01de6e28-6a2e-4023-8048-86cf6e411adf.png">

**Comment by bbernhard** [comment]
The error actually comes from [signal-cli](https://github.com/AsamK/signal-cli). So not sure if I can help much here.

The only two things I can think of are:

* try to delete the signal-cli config directory and start from scratch

* try to invoke the signal-cli command with the `--verbose` flag. This should output more information which could lead you to the    root cause of the issue. i.e:

      `signal-cli --verbose --config /home/.local/share/signal-cli/ link -n signal-api`
      
Apart from that, I can't think of anything else here that might help you resolve the issue. In that case it is probably the best to create an issue in the signal-cli repository.

**Comment by RadovanPelka** [comment]
> 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/29738200/163726148-03872057-f21d-4dd8-b19f-d59c9baf9026.png">

**Comment by cooling75** [comment]
Hi, maybe helpful for someone...  
I had the same problem with "no data to encode" but after setting the image tag to "0.64" (latest) it was working for some reason.  
I am on a K3s cluster and using a [helm chart](https://artifacthub.io/packages/helm/samipsolutions/signal-cli-rest-api) but the image should be the same anyway.

**Comment by itdojo** [comment]
I had this issue and the problem turned out to be a VPN interface (specifically WireGuard) was up.  Turning WireGuard off fixed the problem.

**Comment by EnerGeh** [comment]
@RadovanPelka Did you solve that issue? I'm facing the same problem...

**Comment by ndbu** [comment]
Maybe helpful for others:
I was facing the same issue "Couldn't create QR code: no data to encode".

When connecting to the container, executing sh, I could not touch a file in the driectory /home/.local/share/signal-cli.
# touch /home/.local/share/signal-cli/test
failed.

So I had to change the access rights in the host system of the volume with chmod. Subsequently it worked and I could see that the process created a /data directory in the volume.

Hope this hint helps others.

**Comment by funxiun** [comment]
I happened to have the same problem.
I found out that the main reason (for me) this error occurs is that I'm behind a proxy and Java needs a special proxy configuration for this in the container.

This is how I created a workaround:
I started the docker container in **normal** mode:
`sudo docker run -d --name signal-api --restart=always -p 8080:8080  -v $HOME/.local/share/signal-cli:/home/.local/share/signal-cli  -e 'MODE=normal' bbernhard/signal-cli-rest-api`

In the docker container I added the following line in /usr/bin/signal-cli:

```
# Resolve links: $0 may be a link
app_path=$0

# THE FOLLOWING IS WHAT I'VE ADDED:
export JAVA_OPTS="-Dhttp.proxyHost=proxy.mydomain.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.mydomain.com -Dhttps.proxyPort=8080"

# Need this for daisy-chained symlinks.

```
Of course, use the correct proxy URL/port for your situation.

This works but it is far from elegant because it isn't update proof.
If anyone knows a better solution, let me know.

**Comment by prostheboss** [comment]
I am also getting this when run locally in json-rpc, native and normal mode, not behind a proxy

**Comment by prostheboss** [comment]
> I am also getting this when run locally in json-rpc, native and normal mode, not behind a proxy

[This](https://github.com/bbernhard/signal-cli-rest-api/issues/475#issuecomment-1928485264) fixed it for me

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.
