### ISSUE TITLE
Safety number changed - Howto?

### ISSUE THREAD

**Issue by sirjeannot** [bbernhard/signal-cli-rest-api#34]
[not an issue but couldn't find documentation]
Hello,
upon changing phone, my safety numbers changed. As my profileKey has changed and because signal-cli sets the trust as 0 in the identityKeyStore, I don't receive messages sent by signal-cli on that phone, and signal-cli throws errors when receiving messages from that new phone.
setting the "trustLevel" to 1 after sending a message from the new phone in file .local/share/signal-cli/data/<signal-cli-number> works.
is it the way to do it?
would it be worth it to implement an api call to verify safety numbers?

**Comment by bbernhard** [comment]
> would it be worth it to implement an api call to verify safety numbers?

yeah, that makes definitely sense :+1: 

> is it the way to do it?

Unfortunately, I am not really familiar with all the internal details of [signal-cli](https://github.com/AsamK/signal-cli) (this REST API is just a small wrapper on top of signal-cli, all the heavy lifiting is done by signal-cli). I think you manually fixed the issue by changing the config file, but I think it's not the recommended way to fix the problem (see [here](https://github.com/AsamK/signal-cli/wiki/Manage-trusted-keys))

Until there's an API call for that functionality, you can manually run signal-cli commands from within your docker container. In order to do so, you need to do the following: 

* run `docker ps` to find out the container id of the running signal-cli-rest-api docker container
* run `docker exec -it <containerid> /bin/bash` to connect to the running docker container
* run the signal-cli commands you want to run. e.g: `signal-cli --config /home/.local/share/signal-cli/ -u USERNAME listIdentities -n NUMBER`

**Comment by bbernhard** [comment]
There's now a `trust` endpoint to trust identities.
