### ISSUE TITLE
How to install add-on

### ISSUE THREAD

**Issue by gsportelli** [bbernhard/signal-cli-rest-api#37]
Hi, could you please provide more instructions about how to install the add-on from https://github.com/haberda/hassio_addons?

I've tried to add it to HACS using the UI, but it didn't work. I get a "Repostitory structure for master is not compliant" error.

**Comment by bbernhard** [comment]
Unfortunately, I do not know much about the HASSIO addon. The addon uses the `signal-cli-rest-api` docker image, but was created by @haberda in order to make it more convenient for users to add the Signal integration. If you are experiencing problems with the addon, I guess it's best if you create an issue in the hassio_addons repository.

**Comment by gsportelli** [comment]
Oops, I came to this repo from [here](https://www.home-assistant.io/integrations/signal_messenger/).
For some reason, I thought this image was created for HASSIO, but I now clearly see that it is not the case.
Thank you anyway for the reply.
