### ISSUE TITLE
Authentication before sending message

### ISSUE THREAD

**Issue by gadric** [bbernhard/signal-cli-rest-api#44]
Hi, 

I just got signal-cli-rest-api running for Home Assistant and other purposes. I really like this piece of software. 

However, I just realized that using this command

```
curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "+< my number >", "recipients": ["+< recipiant number >"]}' 'http://<ip address>:8080/v2/send'
```

I can send signal messages from all computers that are in the same network. Security wise this is not optimal. 

Would it possible to add some kind of authentication mechanism? For example a token that needs to be created and attached to the `curl` command in order authorize the sender.

**Comment by bbernhard** [comment]
I also thought about that. I think it shouldn't be that much work to implement a simple token (or username/password) based authentication mechanism. The main reason I haven't it implemented yet is, that I am not sure if it should be part of the `signal-cli-rest-api` in the first place. Don't get me wrong, I am not against that feature - not at all! 

But I am a bit afraid that, once we add that simple feature, the next one wants to have SSL support (which is also perfectly understandable and legitimate). Adding SSL however pulls in a huge complexity into the application, and potentially increases the attack vector (e.g due to a bug in the golang SSL stack). I am wondering whether things like authentication/SSL support can be handled by a reverse proxy? (e.g: https://github.com/nginx-proxy/nginx-proxy). 

So, instead of adding all the complexity to the `signal-cli-rest-api` docker container, the reverse proxy (which is hardened and well maintained in regards to security) handles all that for us. I haven't tried it yet, but I think adding a reverse proxy should work. What do you think?

**Comment by gadric** [comment]
Hmm, 

I understand your approach to keep it simple as this is much better to maintain. 

But it is also work with integrating `signal-cli-rest-api` to other projects for example Home Assistant etc.? I mean having an additional layer mostly makes integration complicated. 

Dont get me wrong. I completely understand to keep this project simple, focus on the core functionality and let other projects focus on security parts.

**Comment by bbernhard** [comment]
> Something just came into my mind. I am not so familiar with reverse proxies. But if you do the authentication and TLS over a reverse proxy, is the signal-cli-rest-api docker container still reachable over IP? If then, then the reverse proxy layer does not add more security, as if you are the in same network, everyone can still send signal messages.

I think that should be possible via docker networks. So, instead of exposing the port where the unprotected REST API listens on, you would expose the API endpoint where the reverse proxy listens. The reverse proxy strips away the authentication information and verifies that the credentials are correct and then forwards the request to the `signal-cli-rest-api`. I haven't tried it yet, but I _think_ that's possible via docker networks. 

> But it is also work with integrating `signal-cli-rest-api` to other projects for example Home Assistant etc.?

Good point, haven't thought about that. I mean, in theory we could still use a reverse proxy (assuming it's really possible to hide the  unprotected port and only expose the protected one) for that. But you are right, that's then more complicated for users to set up. 

Another big advantage of a reverse proxy like nginx is, that you have endless options to configure it to your needs. (e.g basic authentication, token based authentication, SSL support...). On the other hand, what we could also do is to implement a basic authentication method (e.g basic auth or token based authentication) and if someone wants to use something more sophisticated, he/she needs to use a nginx reverse proxy for that. I guess that could be a good compromise. So, if you want to use the Signal Messenger HA integration you can use the built-in authentication and if you want to use `signal-cli-rest-api` standalone, you could use a reverse proxy for more flexibility. 

What do you think?

**Comment by gadric** [comment]
I think this is a good approach to have 2 approach for authentication, at least on the first run. On this way it can be assured that people can test which one works better. 

However, at the end of the day, I think it makes more sense to maintain only 1 approach maybe with an extensive how-to (independently which one). Otherwise too much resources will be invested and I am not a big fan of maintain too many approaches for the same thing. 

BTW.: I will check on reserve approaches in the next couple of days. I will let you know as soon as I have more information.

**Comment by bbernhard** [comment]
> BTW.: I will check on reserve approaches in the next couple of days. I will let you know as soon as I have more information.

Thanks - very much appreciated!

Ultimately I would prefer a nginx based solution. But that requires some good documentation, so that also less technically savvy people can set it up. (it's also less maintenance & implementation effort, as we "just" need to update the HA signal integration + write some documentation). As I am not very good at writing documentation - any help on that front is highly appreciated!

**Comment by bbernhard** [comment]
Authentication is something that's probably not going to implemented soon (as a nginx reverse proxy is fairly easy to set up). In case someone wants to set up a reverse proxy and document the required steps, please let me know. Documentation PRs are always greatly appreciated!

**Comment by oddlama** [comment]
I've just stumbled across this and in case anyone finds this in the future, this is how I made it work:

```nginx
upstream signal-cli-rest-api {
    zone signal-cli-rest-api 64k;
    # Fill in your actual rest server URL here
    server 127.0.0.1:8080;
}

server {
        server_name signal.example.com;
        listen 80;
        listen [::]:80;

        location / {
                return 301 https://$host$request_uri;
        }
}

server {
        server_name signal.example.com;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        # [...] SSL config as usual

	location / {
            auth_basic "Private";
            auth_basic_user_file /etc/nginx/signal.example.com.htpasswd;

            proxy_pass http://signal-cli-rest-api;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```

**Comment by CodeShellDev** [comment]
If you want further Features like Bearer, Basic, Body and Query Auth (+ Path Auth), with per token defined Blocked and Allowed Endpoints, + other QoL features.
Maybe check out this Docker Proxy I made (disclaimer you‘d still need a Reverse Proxy for SSL Certs):
[Github Repo](https://github.com/CODEshelldev/secured-signal-api).
