### ISSUE TITLE
AUTO_RECEIVE_SCHEDULE: Why it's not needed in json-rpc and where are the received messages stored?

### ISSUE THREAD

**Issue by Cangoo** [bbernhard/signal-cli-rest-api#442]
### Feature Request
Hello, first thanks for this project! I came about 2 things I don't quite understand:

1.) I read somewhere else that you might not be able to send messages via Signal if you don't receive messages on a regular base. You are writing that AUTO_RECEIVE_SCHEDULE is not needed in json-rpc-mode. Could you please explain why this is the case? I'm afraid I might not be able to send messages after some time because I plan to use json-rpc. Do I need to trigger receive on my own then regularly? Or is it just not needed?

2.) When using AUTO_RECEIVE_SCHEDULE in normal- or native-mode: Are they just received and discarded? Would be nice to have to option to pass a folder/volume in a setting where these messages could be stored.

**Comment by bbernhard** [comment]
Yes, in json-rpc mode this is not needed, as the messages are automatically received. If you are at that time connected via websocket to the `receive` endpoint you will see the received messages. Otherwise they are gone.

In native/normal mode the AUTO_RECEIVE_SCHEDULE basically calls the `receive` endpoint in a user configureable time interval and discards the messages. You can use that in case you want to keep your Signal installation healthy, but do not care about the received messages. If you want to do something with the received messages, it is better to write your own script, which calls the `receive` endpoint periodically.

**Comment by Cangoo** [comment]
Thanks for the clarification!
