### ISSUE TITLE
Help needed for new install: CAPTCHA proof required 

### ISSUE THREAD

**Issue by Sums123** [bbernhard/signal-cli-rest-api#488]
### The problem

Hi all,

I just started trying to use this tool. I've not yet made the docker compose setup, but rather worked with the docker run instructions that are listed in the readme. Whenever I try to send a message I get the error message below. I saw [this ](https://github.com/bbernhard/signal-cli-rest-api/issues/437#issuecomment-1957468599) post but not sure if it is the suggested solution, or if I should follow the error message instructions.

Nevertheless I'm a bit confused on how to proceed. Does it matter from where I get the signalcaptcha or should I receive it from the host system? This will be challenging since I am running the API in a headless VM. I tried to run it from my usual environment and copy pasting the values to the vm, but without success.

Do I understand correctly that the challenge token doesn't need to be submitted at all when solving the Captcha?  Why is there a number "1708626655902" listed in the instructions from the error message?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

other

### Additional information

`curl -X POST -H "Content-Type: application/json" 'http://10.10.1.21:9922/v2/send'      -d '{"message": "Hi Martin, die Nachricht schicke ich über WikiMore!", "number": "+XXXX", "recipients": [ "YYYY" ]}'
{"error":"Failed to send (some) messages:\n+XXXX: CAPTCHA proof required for sending to \"+XXXX\", available options \"RECAPTCHA, PUSH_CHALLENGE\" with challenge token \"37ec470f-2774-4457-9e96-2da1acbb9c83\", or wait \"86400\" seconds.\nTo get the captcha token, go to https://signalcaptchas.org/challenge/generate.html\nAfter solving the captcha, right-click on the \"Open Signal\" link and copy the link.\nUse the following command to submit the captcha token:\nsignal-cli submitRateLimitChallenge --challenge CHALLENGE_TOKEN --captcha CAPTCHA_TOKEN\n1708626655902\nINFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.\nFailed to send message due to rate limiting\n"}
`

**Comment by bbernhard** [comment]
> The Signal protocol expects that incoming messages are regularly received.

In `normal` or `native` mode you need to call the `receive` endpoint regularily. Either write your own script, that calls the endpoint periodically or use the [Auto Receive Schedule](https://github.com/bbernhard/signal-cli-rest-api?tab=readme-ov-file#auto-receive-schedule).

Regarding the rate limiting challenge:

* open https://signalcaptchas.org/challenge/generate.html in the browser (can be on any host)
* open the developer console in your browser
* Solve the captcha
* On the developer console, find the line that looks like this: `Prevented navigation to “signalcaptcha://{captcha value}” due to an unknown protocol.` Copy the captcha value
* use the captcha value and the challenge token (the challenge token can be found in the output you've posted. in your example: `37ec470f-2774-4457-9e96-2da1acbb9c83` and call the `rate-limit-challenge` endpoint (https://bbernhard.github.io/signal-cli-rest-api/#/Accounts/post_v1_accounts__number__rate_limit_challenge)

**Comment by Sums123** [comment]
Thanks, with your help I was trying to get it to work :)

I think maybe I had some error in my curl syntax before, or I was too slow to enter the very long captcha token.

For me I also had to use the copy link path, I didn't have that console output, probably because signal is a registered protocol on my system
![image](https://github.com/bbernhard/signal-cli-rest-api/assets/29928499/3dff5436-ad17-4b18-a823-51f95b870a92)

**Comment by Sums123** [comment]
Oof after sending one message I get the same error message as before :/

**Comment by Sums123** [comment]
Ok after calling /v1/receive I could send another message. I will try to follow your advice and use that endpoint regularly. Thanks!
