### ISSUE TITLE
can't find a unregister endpoint

### ISSUE THREAD

**Issue by narimantos** [bbernhard/signal-cli-rest-api#518]
### The problem

I have started the signal-rest-api in `json-rpc` mode but i can't find a way to unregister. 
What happens if i don't unregister and remove the config data for the registered number? 

Can i register it again later on? What/when do I actually need to unregister?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
You should be able to re-register the number later. Although the `unregister` is not yet exposed, you can still do it, by calling the appropriate [signal-cli command](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc) directly. In order to do so, first switch to the `normal` mode and then do the following:

* find the container id of the running docker container with `docker ps`
* connect to the running docker container with: `docker exec -it <container id> /bin/bash`
* run `su signal-api` inside the docker container
* call the signal-cli `unregister` command with: `signal-cli -a <+number> --config /home/.local/share/signal-cli unregister`
