### ISSUE TITLE
Users that re-register account and rejoin groups do not get messages

### ISSUE THREAD

**Issue by thedeadliestcatch** [bbernhard/signal-cli-rest-api#542]
### The problem

In the event that a member of a group re-registers the account to a new number, signal-cli-rest-api seems to go out of sync and that person no longer receivers any message sent to that group by the signal-cli-rest-api account.

I verified through linking an instance of the Desktop app that the user is trusted and marked as verified.

Adding the signal-cli-rest-api account to a new account also does *not* reflect in the `v1/groups/[account]` endpoint.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
For all the points you've raised we probably need to find out whether those are actual issues of the REST API wrapper or if those are limitations/issues of [signal-cli](https://github.com/AsamK/signal-cli) - which does all the heavy lifting.

> If the users are withholding their phone number via privacy settings/PNP, the members array comes with blank strings ("") for each one of those members in the groups endpoints.

Could you maybe enable the [Debug Mode](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and report back what signal-cli returns in that case. For some reason I can't reproduce that issue here :thinking:
