### ISSUE TITLE
New Api call: UpdateGroup

### ISSUE THREAD

**Issue by ed-holland** [bbernhard/signal-cli-rest-api#67]
I've created a group successfully. Problem is that it still thinks the members have registration pending. As such, no message a received by them. 
Looking from the members perspective, they have confirmed the registration.

Signal-cli has the command "updateGroup" which should resolve these issues.

This is already used to create a group. Updating it (also to add more members) is currently not.

Can this call be added?

**Comment by bbernhard** [comment]
If I understood you correctly, then you are creating the group via the REST API, right? In that case there shouldn't be any additional `updateGroup` call necessary. Afaik this is only needed if someone else creates a group and you want to join it via the API. Or is that what you are doing?

**Comment by ed-holland** [comment]
Yes, the group was created using the REST api. I have received the group id.
Then confirmed the group in the member added.
Status stayed the same though and no messages were received when sending to the group.

Sending to the group with rest api showed no errors.

I've tried to do the updateGroup from the cli but it keeps saying that the group id is wrong (testet without the "group." prefix). Tried also with quitGroup and send with the same result.
The listGroup shows the group and the internal ID (converted to Base64) matches the one of the create.

Not sure what to thing about it.

**Comment by bbernhard** [comment]
That's odd. I've tried the same and for me sending to a group works without doing anything special.

> The listGroup shows the group and the internal ID (converted to Base64) matches the one of the create.

The internal id is the one that is used by signal-cli. In order to make it more convenient for users and to avoid that users need  to URL-escape the internal id is converted to base64. So, if you want to interact with signal-cli directly without the REST APi, please use the internal id. 

> Sending to the group with rest api showed no errors.

Okay, that looks like as if the request was successful - otherwise signal-cli would have complained. 

How many members does your group have? If you have multiple members, you could try to limit it to one - maybe that narrows down the problem a bit.

**Comment by ed-holland** [comment]
> > The listGroup shows the group and the internal ID (converted to Base64) matches the one of the create.
> 
> The internal id is the one that is used by signal-cli. In order to make it more convenient for users and to avoid that users need to URL-escape the internal id is converted to base64. So, if you want to interact with signal-cli directly without the REST APi, please use the internal id.

Just tried that also. It give the error `Failed to send message: Conflict`

The group has currently only one member. More to follow when HA is notifying correctly.
As i only have one member in the group... no message arrives. I can send to that member directly without a problem.

**Comment by bbernhard** [comment]
see: https://github.com/bbernhard/signal-cli-rest-api/issues/54#issuecomment-762848311

**Comment by bbernhard** [comment]
see: https://github.com/bbernhard/signal-cli-rest-api/issues/54#issuecomment-762848311

**Comment by bbernhard** [comment]
There's now a docker test image available, that implements the possibility to join/block/quit groups. If you want to give it a try, you have to change your docker image to `bbernhard/signal-cli-rest-api:0.49-dev` 

(Don't forget to change the image back once the stable version is released, otherwise you will be stuck at that version)

**Comment by bbernhard** [comment]
The latest stable release now includes the possiblity to join/block/quit Signal Groups.

In case it still doesn't work for you, please open another ticket.

**Comment by ed-holland** [comment]
FYI: with v34 the issue (registration pending) was still there until I did a "Receive".

After that, the group member was accepted. Sending messages is not problem anymore :-)

**Comment by bbernhard** [comment]
> FYI: with v34 the issue (registration pending) was still there until I did a "Receive".
> 
> After that, the group member was accepted. Sending messages is not problem anymore :-)

Thanks, I've added it to the [Troubleshooting](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/TROUBLESHOOTING.md) page.
