### ISSUE TITLE
Unregister api

### ISSUE THREAD

**Issue by jyothisjose** [bbernhard/signal-cli-rest-api#71]
I could able to register a number using https://127.0.0.1:8080/v1/unregister/+xxxxxxxxxx.
Is it possible to unregister the registered number?

**Comment by bbernhard** [comment]
What do you mean by unregister? Have you messed something up and want to start from scratch or do you want to delete the number associated with the signal service?

**Comment by AT0myks** [comment]
I think @jyothisjose is talking about [this](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#unregister) which is something I would also like to be added to this great project (with the `--delete-account` option preferably).

**Comment by macbih** [comment]
@bbernhard:

> Have you messed something up and want to start from scratch or do you want to delete the number associated with the signal service?

I would like to delete the number association. I need to unregister my landline number as people have started sending messages to it. Their phones have reported to them that my landline number is a Signal number. Although this is technically true, it keeps confusing the people as they send messages that won't be answered or reacted to ever. My original intention was to send messages from my home automation. Thank you!

Is there a way to deregister a number?

**Comment by bbernhard** [comment]
> @bbernhard:
> 
> > Have you messed something up and want to start from scratch or do you want to delete the number associated with the signal service?
> 
> I would like to delete the number association. I need to unregister my landline number as people have started sending messages to it. Their phones have reported to them that my landline number is a Signal number. Although this is technically true, it keeps confusing the people as they send messages that won't be answered or reacted to ever. My original intention was to send messages from my home automation. Thank you!
> 
> Is there a way to deregister a number?

There's no API endpoint yet. But you can connect to the docker container and invoke the signal-cli command directly. In order to do this, make sure to run the docker container either in normal or native mode. Then:

* get the container id of the running container with `docker ps`
* connect to the running docker container with `docker exec -it <container id> /bin/bash`
Now you are inside the docker container
* run `su signal-api` to switch to the `signal-api` user
* Now you can run any [signal-cli command](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#unregister)

**Comment by AT0myks** [comment]
Thank you for adding it!
