### ISSUE TITLE
Is there some webhook mechanism for receive messages

### ISSUE THREAD

**Issue by dickyj** [bbernhard/signal-cli-rest-api#74]
Hi Bernhard,
Thanks for the great contribution here. I was just wondering, for receiving message api, I still do not understand how to use it. Do we keep polling for new messages? Or is there a webhook that can notify us of new messages?

Dicky

**Comment by bbernhard** [comment]
I am afraid, at the moment the only possibility is to poll the API in regular intervals. In theory it would be possible to use webhooks (or other mechanisms), but the problem here is that `signal-cli` doesn't support to be run in DBUS mode and normal cli mode (see [here](https://github.com/AsamK/signal-cli/issues/446) for details). If polling is too slow for you and receiving messages is your primary use case, you could consider ditching the REST API and use `signal-cli` directly in DBUS mode.

**Comment by dickyj** [comment]
Ok,
No problem. With webhook its just better performance thats all.

**Comment by blackham** [comment]
Sorry to comment on old/closed issues but maybe this could be reopened. 

There have been some updates to singal-cli since this was last talked about. (Support for: JSON-RPC). I'm curious if these news features would make it possible to add a webhook ability. 

As for a comment @bbernhard made in the signal-cli issue/chat regarding handling storage of these messages, my thought would be to either: 
1) Just try and send the message to the webhook URL and ignore any 400/500 errors. (Fire and forget).
2) If you do want to be friendly, just have a message queue in memory. When the webhook endpoint comes back on line send what you got in the order you got it. If a message was edited/deleted that event will be in the queue. It will be up to the app on the other end of the webhook to handle it. 

 I'm looking to add the ability to listen for commands and execute them via signal. Like me sending the signal message  "kick it" to my signal-cli-rest-api bot. The bot would then verify I'm a trusted admin and then run "/etc/init.d apache2 restart".  (And no I don't want to wait n seconds between each cron "receive" pull) 
 
 I would like to use singal-cli-rest-api to simplify linking the signal account with the bot. And then after that, just watch every incoming message for special commands from trusted signal accounts. On that note, I wouldn't mind it if after a signal device was linked that all the DBus or JSON-RPC messages were just sent raw to another TCP port. In my case I'm only reading.  
 
 Crossing my fingers.. 
 And thanks for your work on a much needed API to singal.

**Comment by jon011235** [comment]
@bbernhard I would also love this! Is this somehow feasible?

Thanks for all your hard work! It is great!
