### ISSUE TITLE
New API calls : Pending invitations + accept/delete-refuse invitations

### ISSUE THREAD

**Issue by sirjeannot** [bbernhard/signal-cli-rest-api#75]
Hello,

everything is in the topic.
Since deployment of the new groups, this becomes necesarry.
For some reason even if the client using signal-cli has not accepted the invitation to a group, it can still send content to that group.

As always, thank you very much for your work, muck much appreciated.

Take care.

**Comment by legomind** [comment]
Hate commenting to leave a +1, but this is also an issue for me.

**Comment by bbernhard** [comment]
There's now a docker test image available, that implements the possibility to join/block/quit groups. If you want to give it a try, you have to change your docker image to `bbernhard/signal-cli-rest-api:0.49-dev` 

(Don't forget to change the image back once the stable version is released, otherwise you will be stuck at that version)

**Comment by legomind** [comment]
@bbernhard works great! Was able to join a V2 group with ease.

**Comment by bbernhard** [comment]
> @bbernhard works great! Was able to join a V2 group with ease.

great, many thanks for testing!

**Comment by bbernhard** [comment]
just fyi: The latest stable release now contains the above changes.

**Comment by sirjeannot** [comment]
as usual, thank you!
