### ISSUE TITLE
Feature Request for Receive

### ISSUE THREAD

**Issue by meltedhaggis** [bbernhard/signal-cli-rest-api#8]
Sorry this isn't an issue, I saw at the bottom you mentioned to create a pull request for new functionality but I'm unsure how to do that, would there be any chance to implement receiving messages, I've attempted to use signal-cli inside the container to receive but i get unregistered error.

Thank you

**Comment by bbernhard** [comment]
With the latest version it should be possible to receive messages. I've updated the `README` with an example.

**Comment by meltedhaggis** [comment]
beautiful I can't wait to get in about that, thanks very much by far my favourite docker, I've actually just ran into an issue I messed my phone up last night and had to reset it, I'm now receiving an error 413 Rate limit exceeded, I've done a bit of research and I believe its because my security number has changed now, is there any way to accept that or move forward? I guess I can just reset the docker if there isn't a proper way to deal with it.

**Comment by bbernhard** [comment]
I haven't experienced this type of error yet, but you could try to register the SIM card again. In order to do that, you first have to delete the cryptographic keys, otherwise the registration with the `/v1/register` endpoint won't work. The cryptographic keys are stored in the `signal-cli-config` directory. If you use [this](https://github.com/bbernhard/signal-cli-rest-api/blob/master/docker-compose.yml) `docker-compose.yml` the folder should be in the same directory as the `docker-compose.yml` file. Inside the `signal-cli-config` directory there's a `data` directory. This `data` directory needs to be deleted. Then you can re-register your SIM card as described in the `README`.

In case you are using docker-volumes, you can also just destroy that in order to start from scratch.

**Comment by meltedhaggis** [comment]
i didn't i installed it as a container so I could start it at boot easier, I usually use lxc's this is my first stab at docker not a fan tbh but barley getting to grips with it, i did a find on the host and deleted the files  you suggested from the docker file system and i'm back up and running, thanks very much!

**Comment by bbernhard** [comment]
I'll close this one - in case you run into problems please re-open.
