### ISSUE TITLE
Show swagger as add-on UI

### ISSUE THREAD

**Issue by mdegat01** [bbernhard/signal-cli-rest-api#88]
### Feature Request

The curl requests make it a bit challenging to get going with your add-on currently. Not impossible by any means since its mostly just copy and paste (although I did have to go hunting around in the [issues](https://github.com/bbernhard/signal-cli-rest-api/issues/19) for instructions on how to deal with the captcha). And then afterwards I was hoping to just try it out by making and deleting some groups, sending some messages, etc. and was looking for a faster way to do so then writing out `curl` requests or restarting HA with new REST commands or notify RESTS.

When I came across [the swagger spec](https://bbernhard.github.io/signal-cli-rest-api/#/) I realized you already had a great answer. The add-on could just show that exact web page as the UI for the add-on but with the base URL set to HA's `internal_url`, instead of `127.0.0.1` which is only accessible when executing commands literally from that machine. Could do this as either ingress UI or as a separate webpage, either way would allow for a lot quicker testing/trying out in my opinion.

Just a thought, not sure how difficult it is. I may look into it myself this weekend if I get some time although I have never really worked on an add-on before. Another alternative would be a downloadable [postman collection](https://www.postman.com/collection/) from the readme if adding a UI is harder then I'm giving it credit for.

Either way, thanks for the great add-on!  Really useful.

**Comment by mdegat01** [comment]
Shoot I just realized this is probably in the wrong repo and should be [here](https://github.com/haberda/hassio_addons). I'm not sure how to move it though and am on my phone now. Sorry about that

**Comment by bbernhard** [comment]
Thanks for the feature request!

As you already mentioned, the issue is probably better suited in @haberda's repository. I had a quick look in the github docs and moving issues is unfortunately only possible when both repos are owned by the same person. So I guess you have to either create a new issue there and copy the whole description over, or just create a new issue and link to this issue here.

Regarding the documentation: Yeah, the documentation is definitely one of the weak points with a lot of room for improvement. As a developer it's always a bit hard to detect the places where documentation is lacking/can be improved. If you have any suggestions on how to improve the onboarding - feel free to create a pull request. Any help with that would be great and highly appreciated!

**Comment by mdegat01** [comment]
Remade it [here](https://github.com/haberda/hassio_addons/issues/18) in the correct repo
