### ISSUE TITLE
QRCode link: please provide a name for a device

### ISSUE THREAD

**Issue by MatejKovacic** [bbernhard/signal-cli-rest-api#95]
So I installed signal-cli-rest-api ad addon on my Home Assistant and when I go to `http://192.168.200.245:8080/v1/about` I get nice message:
```
{
    "versions": [
        "v1",
        "v2"
    ],
    "build": 2
}
```
Now I want to register additional device to my existing signal number So I say:

`http://192.168.200.245:8080/v1/qrcodelink`. Documentation says "No parameters".

Unfortunately I get this:
```
{
    "error": "Please provide a name for the device"
}
```

Any help on this?

**Comment by MatejKovacic** [comment]
Some additional info, log from HomeAssistant:

```
time="2021-02-16T15:13:16+01:00" level=info msg="Started Signal Messenger REST API"
[GIN] 2021/02/16 - 15:13:23 | 404 |       3.229µs | 192.168.200.254 | GET      "/"
[GIN] 2021/02/16 - 15:14:44 | 200 |     6.19831ms | 192.168.200.254 | GET      "/v1/about"
[GIN] 2021/02/16 - 15:43:11 | 400 |     318.644µs | 192.168.200.254 | GET      "/v1/qrcodelink"
[GIN] 2021/02/16 - 15:48:26 | 400 |   16.430199ms | 192.168.200.254 | GET      "/v1/qrcodelink"
```

**Comment by bbernhard** [comment]
Oh, looks like the swagger documentation was incomplete. You need to specify a device name with `?device_name=xxx`

e.g:
`http://127.0.0.1:8080/v1/qrcodelink?device_name=mydevice`

**Comment by MatejKovacic** [comment]
OK, now it shows QR code, but when I try to link this QR code (this device) with existing Android installation of Signal, it (Android) says that no device has been found.

**Comment by bbernhard** [comment]
I think this could be related to this issue here: https://github.com/AsamK/signal-cli/issues/365

What you could do is, connect inside the running docker container and execute the appropriate `signal-cli` command manually. 

So, it's basically: 

* find the docker container id of the signal-cli-rest-api docker container with `docker ps`
* connect to the docker container by running `docker exec -it <container id> /bin/bash`
* execute `su signal-api` inside the docker container
* execute the `signal-cli` command mentioned in the ticket. Don't forget to specify the correct signal-cli config location with the `--config` parameter
* copy the generated QR code from inside the docker container to the host system with `docker cp`
* open the generated QR code on the host system and scan it with your Android device

**Comment by MatejKovacic** [comment]
I executed the signal-cli command:
`signal-cli link -n "Server" | xargs -l qrencode -o /tmp/qrcode.png --level=H -v 10 & while [ ! -f /tmp/qrcode.png ]; do sleep 1; done; xdg-open /tmp/qrcode.png;`

This is what I got:
```
[1] 253
xargs: qrencode: No such file or directory
[1]+  Exit 127                signal-cli link -n "Server" | xargs -l qrencode -o /tmp/qrcode.png --level=H -v 10
```
It seems there is some error with xargs?

**Comment by MatejKovacic** [comment]
OK, I found out the problem. `qrencode` should be installed, because it is not.
